"""Account-interface translations; submitted content is never translated here."""

ACCOUNT_COPY = {'en': {'write_title': 'Write a story',
        'community_stories': 'COMMUNITY STORIES',
        'write_intro': 'Be the reporter of your own work. Share what happened, what you learned, and how '
                       'others can take part.',
        'back_feed': 'Back to the feed',
        'post_project': 'Post your project',
        'manage_news': 'Manage automatic project news',
        'signed_in': 'Signed in as',
        'sign_out': 'Sign out',
        'preview_unpublished': 'PREVIEW · NOT PUBLISHED',
        'self_reported': 'Self-reported',
        'take_part': 'How to take part',
        'evidence': 'Evidence links',
        'link': 'Link',
        'no_evidence': 'Self-reported · No evidence link supplied.',
        'show_original': 'Show original text',
        'your_update': 'Your update',
        'english_notice': 'Write the headline and update in English. Your text is published as written; '
                          'other editions show translation notices until translations are available.',
        'project_name': 'Project name',
        'optional': '(optional)',
        'project_example': 'e.g. Open Civic Map',
        'headline': 'Headline (English)',
        'headline_placeholder': 'A short, factual headline',
        'description': 'What happened (English)',
        'description_placeholder': 'What did you do? What changed?',
        'take_part_placeholder': 'Where to join and what help is needed',
        'hashtags': 'Hashtags',
        'hashtag_help': 'Up to eight tags, separated by spaces or commas. Each tag opens a timeline of '
                        'related stories. Letters in any language, numbers, hyphens and underscores are '
                        'welcome.',
        'optional_line': '(optional, one per line)',
        'evidence_help': 'Up to five public links: pull requests, meeting notes, or event pages. Stories '
                         'without evidence links are labeled as having no source.',
        'original': 'Original text',
        'optional_language': '(optional, any language)',
        'original_placeholder': 'Keep the original post or notes alongside your story',
        'event_date': 'Date it happened',
        'optional_today': '(optional, defaults to today)',
        'author': 'Public display name',
        'story_consent': 'This is my work or I am authorized to share it. I agree to publish this story, its '
                         'links, original text, and my display name publicly.',
        'story_limit': 'Google verifies your account; the story is self-reported. You can publish up to five '
                       'stories or projects every 24 hours.',
        'preview_story': 'Preview story',
        'retry_story': 'Retry publishing saved story',
        'publish_story': 'Publish story',
        'stories_footer': 'Community stories, shared by the people doing the work.',
        'community_projects': 'COMMUNITY PROJECTS',
        'submit_heading': 'Share what you’re building.',
        'submit_intro': 'Post your civic-tech project to the rep0rter community feed.',
        'submit_notice': 'Your description will be published as written to the website and RSS feed, labeled '
                         'as an owner submission.',
        'project_url': 'Project website or repository',
        'project_description': 'Project description',
        'project_description_help': 'What does it do, who is it for, and how can people help? Up to 3,000 '
                                    'characters.',
        'description_language': 'Description language',
        'project_consent': 'I own this project or am authorized to represent it, and I agree to publish this '
                           'description, link, and display name publicly.',
        'project_limit': 'Google sign-in verifies your account. Project ownership is self-declared. You can '
                         'publish up to five projects every 24 hours.',
        'retry_project': 'Retry publishing saved project',
        'publish_project': 'Publish project to the feed',
        'projects_footer': 'Community projects, shared by the people building them.',
        'project_news': 'Your project news',
        'newsroom': 'YOUR PROJECT NEWSROOM',
        'news_heading': 'You run the project. Your news runs here.',
        'news_intro': 'Write a template once. Publish news automatically when your project has something new '
                      'to share.',
        'one_off': 'Write a one-off post',
        'add_project': 'Add a project',
        'saved': 'Project settings saved.',
        'auto_enabled': 'Automatic publishing is enabled for new updates.',
        'auto_paused': 'Automatic publishing is paused.',
        'your_projects': 'Your projects',
        'auto_every': 'Automatic · every {hours}h',
        'paused': 'Paused',
        'template_preview': 'Template preview · example update',
        'sample_notice': 'This is sample content. Previewing does not save settings or publish a post.',
        'edit_news': 'Edit project news',
        'setup_news': 'Set up project news',
        'latest_update': 'Latest published update',
        'website': 'Project website',
        'news_language': 'News language',
        'source_kind': 'Where should news come from?',
        'github_releases': 'GitHub releases',
        'rss_feed': 'RSS news feed',
        'source_url': 'GitHub repository or RSS URL',
        'source_placeholder': 'your-team/your-project or https://your-project.org/feed.xml',
        'source_help': 'Use a public repository or an HTTPS RSS 2.0 feed that you maintain. GitHub drafts '
                       'and pre-releases are excluded.',
        'headline_template': 'News headline template',
        'summary_template': 'News body template',
        'template_help': 'Use $project for your project name, $title for the update title, $summary for its '
                         'description, and $url for its source link. Use $$ for a dollar sign. Posts must '
                         'fit within 160 headline characters and 3,000 body characters.',
        'check_updates': 'Check for new updates',
        'hourly': 'Every hour',
        'six_hourly': 'Every 6 hours',
        'daily': 'Every day',
        'enable_auto': 'Automatically publish new updates to the website and RSS feed.',
        'auto_help': 'Only updates dated after you enable publishing are included. Uncheck this option and '
                     'save to pause. Each account can publish five posts per 24 hours across all its '
                     'projects.',
        'auto_consent': 'I own or represent this project and its news source, and authorize public posts '
                        'using this template and display name. Ownership is self-declared.',
        'preview_example': 'Preview with an example',
        'save_settings': 'Save project settings',
        'news_footer': 'Project news is published from your template, with a link to each original update.',
        'community_nav': 'Community navigation'},
 'zh-TW': {'write_title': '撰寫報導',
           'community_stories': '社群報導',
           'write_intro': '成為自己工作的記者。分享發生的事、學到的經驗，以及大家如何參與。',
           'back_feed': '返回消息列表',
           'post_project': '分享專案',
           'manage_news': '管理自動發布消息',
           'signed_in': '登入身分',
           'sign_out': '登出',
           'preview_unpublished': '預覽 · 尚未發布',
           'self_reported': '作者自行提供',
           'take_part': '如何參與',
           'evidence': '佐證連結',
           'link': '連結',
           'no_evidence': '作者自行提供 · 未附佐證連結。',
           'show_original': '顯示原始文字',
           'your_update': '你的消息',
           'english_notice': '請以英文撰寫標題及消息內容。文字將原文發布；其他語言版本在翻譯完成前會顯示翻譯提示。',
           'project_name': '專案名稱',
           'optional': '（選填）',
           'project_example': '例如：Open Civic Map',
           'headline': '標題（英文）',
           'headline_placeholder': '簡短、客觀的英文標題',
           'description': '發生什麼事（英文）',
           'description_placeholder': '你做了什麼？帶來哪些改變？',
           'take_part_placeholder': '在哪裡加入？需要什麼協助？',
           'hashtags': '主題標籤',
           'hashtag_help': '最多八個標籤，以空格或逗號分隔。每個標籤可開啟相關報導的時間軸。可使用各種語言的文字、數字、連字號與底線。',
           'optional_line': '（選填，每行一個）',
           'evidence_help': '最多五個公開連結，例如 Pull Request、會議紀錄或活動頁面。未提供佐證連結的報導將標示為無來源。',
           'original': '原始文字',
           'optional_language': '（選填，不限語言）',
           'original_placeholder': '在報導旁保留原始貼文或筆記',
           'event_date': '發生日期',
           'optional_today': '（選填，預設為今天）',
           'author': '公開顯示名稱',
           'story_consent': '這是我的工作成果，或我已獲授權分享。我同意公開發布這篇報導、連結、原始文字及顯示名稱。',
           'story_limit': 'Google 僅驗證帳號；報導內容由作者自行提供。每 24 小時最多可發布五篇報導或專案。',
           'preview_story': '預覽報導',
           'retry_story': '重新發布已儲存的報導',
           'publish_story': '發布報導',
           'stories_footer': '由實際參與者分享的社群報導。',
           'community_projects': '社群專案',
           'submit_heading': '分享你正在打造的事物。',
           'submit_intro': '將你的公民科技專案分享到 rep0rter 社群消息列表。',
           'submit_notice': '你的說明將原文發布到網站及 RSS，並標示為專案擁有者投稿。',
           'project_url': '專案網站或程式碼儲存庫',
           'project_description': '專案說明',
           'project_description_help': '專案做什麼、服務誰，以及大家如何協助？最多 3,000 字元。',
           'description_language': '說明使用的語言',
           'project_consent': '我擁有此專案或獲授權代表專案，並同意公開發布這份說明、連結與顯示名稱。',
           'project_limit': 'Google 登入僅驗證帳號，專案所有權由投稿者自行聲明。每 24 小時最多可發布五個專案。',
           'retry_project': '重新發布已儲存的專案',
           'publish_project': '將專案發布到消息列表',
           'projects_footer': '由打造專案的人分享的社群成果。',
           'project_news': '你的專案消息',
           'newsroom': '你的專案編輯台',
           'news_heading': '你經營專案，這裡發布消息。',
           'news_intro': '設定一次範本，專案有新進展時就能自動發布消息。',
           'one_off': '撰寫單次投稿',
           'add_project': '新增專案',
           'saved': '已儲存專案設定。',
           'auto_enabled': '新消息的自動發布已啟用。',
           'auto_paused': '自動發布已暫停。',
           'your_projects': '你的專案',
           'auto_every': '自動發布 · 每 {hours} 小時',
           'paused': '已暫停',
           'template_preview': '範本預覽 · 範例消息',
           'sample_notice': '這是範例內容。預覽不會儲存設定，也不會發布貼文。',
           'edit_news': '編輯專案消息',
           'setup_news': '設定專案消息',
           'latest_update': '最近發布的消息',
           'website': '專案網站',
           'news_language': '消息使用的語言',
           'source_kind': '消息要從哪裡取得？',
           'github_releases': 'GitHub 發行版本',
           'rss_feed': 'RSS 消息訂閱',
           'source_url': 'GitHub 儲存庫或 RSS 網址',
           'source_placeholder': 'your-team/your-project 或 https://your-project.org/feed.xml',
           'source_help': '請使用你維護的公開儲存庫或 HTTPS RSS 2.0 訂閱來源。不包含 GitHub 草稿及預先發行版本。',
           'headline_template': '消息標題範本',
           'summary_template': '消息內文範本',
           'template_help': '以 $project 代表專案名稱、$title 代表更新標題、$summary 代表說明、$url 代表來源連結。美元符號請使用 $$。標題不得超過 160 '
                            '字元，內文不得超過 3,000 字元。',
           'check_updates': '檢查新消息',
           'hourly': '每小時',
           'six_hourly': '每 6 小時',
           'daily': '每天',
           'enable_auto': '自動將新消息發布到網站與 RSS。',
           'auto_help': '只會發布啟用後的新消息。取消勾選並儲存即可暫停。每個帳號的所有專案合計每 24 小時最多發布五篇。',
           'auto_consent': '我擁有或代表此專案及其消息來源，並授權使用此範本與顯示名稱公開發布。所有權由本人自行聲明。',
           'preview_example': '使用範例預覽',
           'save_settings': '儲存專案設定',
           'news_footer': '專案消息依照你的範本發布，並附上每則更新的原始連結。',
           'community_nav': '社群導覽'},
 'ja': {'write_title': '記事を書く',
        'community_stories': 'コミュニティの記事',
        'write_intro': '自分の活動を自分の言葉で伝えましょう。出来事や学び、参加方法を共有できます。',
        'back_feed': '記事一覧に戻る',
        'post_project': 'プロジェクトを紹介',
        'manage_news': '自動配信を管理',
        'signed_in': 'ログイン中：',
        'sign_out': 'ログアウト',
        'preview_unpublished': 'プレビュー · 未公開',
        'self_reported': '投稿者による報告',
        'take_part': '参加方法',
        'evidence': '参考リンク',
        'link': 'リンク',
        'no_evidence': '投稿者による報告 · 参考リンクはありません。',
        'show_original': '原文を表示',
        'your_update': '伝えたいこと',
        'english_notice': '見出しと本文は英語で書いてください。入力した文章がそのまま公開されます。他言語版では翻訳ができるまで案内が表示されます。',
        'project_name': 'プロジェクト名',
        'optional': '（任意）',
        'project_example': '例：Open Civic Map',
        'headline': '見出し（英語）',
        'headline_placeholder': '簡潔で事実に即した英語の見出し',
        'description': '何があったか（英語）',
        'description_placeholder': '何をしましたか？何が変わりましたか？',
        'take_part_placeholder': '参加先と必要な協力について',
        'hashtags': 'ハッシュタグ',
        'hashtag_help': '空白またはカンマで区切って最大8個。タグから関連記事の時系列一覧を開けます。各言語の文字、数字、ハイフン、アンダースコアが使えます。',
        'optional_line': '（任意、1行に1件）',
        'evidence_help': 'プルリクエスト、議事録、イベントページなどの公開リンクを最大5件。参考リンクがない記事には出典なしと表示されます。',
        'original': '原文',
        'optional_language': '（任意、言語不問）',
        'original_placeholder': '元の投稿やメモを記事と一緒に残せます',
        'event_date': '出来事の日付',
        'optional_today': '（任意、未入力なら今日）',
        'author': '公開表示名',
        'story_consent': 'これは自分の活動、または共有の許可を得た活動です。記事、リンク、原文、表示名の公開に同意します。',
        'story_limit': 'Googleが確認するのはアカウントです。記事内容は投稿者による報告です。記事またはプロジェクトを24時間に最大5件公開できます。',
        'preview_story': '記事をプレビュー',
        'retry_story': '保存済み記事の公開を再試行',
        'publish_story': '記事を公開',
        'stories_footer': '活動する人たちが伝える、コミュニティの記事。',
        'community_projects': 'コミュニティのプロジェクト',
        'submit_heading': '取り組んでいることを共有しましょう。',
        'submit_intro': 'シビックテックのプロジェクトをrep0rterのコミュニティに紹介しましょう。',
        'submit_notice': '説明文は入力したままウェブサイトとRSSに公開され、所有者からの投稿と表示されます。',
        'project_url': 'ウェブサイトまたはリポジトリ',
        'project_description': 'プロジェクトの説明',
        'project_description_help': '何をするものか、誰のためか、どのように協力できるかを3,000文字以内で。',
        'description_language': '説明文の言語',
        'project_consent': 'このプロジェクトの所有者、または正式な代理人であり、説明文、リンク、表示名の公開に同意します。',
        'project_limit': 'Googleログインでアカウントを確認します。所有権は自己申告です。24時間に最大5件のプロジェクトを公開できます。',
        'retry_project': '保存済みプロジェクトの公開を再試行',
        'publish_project': 'プロジェクトを公開',
        'projects_footer': '作り手が紹介する、コミュニティのプロジェクト。',
        'project_news': 'プロジェクトのニュース',
        'newsroom': 'プロジェクトの編集室',
        'news_heading': 'プロジェクトの最新情報を、ここから。',
        'news_intro': 'テンプレートを一度書けば、新しい情報を自動で公開できます。',
        'one_off': '単発の投稿を書く',
        'add_project': 'プロジェクトを追加',
        'saved': '設定を保存しました。',
        'auto_enabled': '新しい更新の自動公開が有効です。',
        'auto_paused': '自動公開は一時停止中です。',
        'your_projects': 'あなたのプロジェクト',
        'auto_every': '自動 · {hours}時間ごと',
        'paused': '一時停止中',
        'template_preview': 'テンプレートのプレビュー · 更新例',
        'sample_notice': 'これはサンプルです。プレビューでは設定の保存や投稿の公開は行いません。',
        'edit_news': 'ニュース設定を編集',
        'setup_news': 'ニュース配信を設定',
        'latest_update': '最新の公開済みニュース',
        'website': 'プロジェクトのウェブサイト',
        'news_language': 'ニュースの言語',
        'source_kind': 'ニュースの取得元',
        'github_releases': 'GitHubリリース',
        'rss_feed': 'RSSニュースフィード',
        'source_url': 'GitHubリポジトリまたはRSS URL',
        'source_placeholder': 'your-team/your-project または https://your-project.org/feed.xml',
        'source_help': '管理している公開リポジトリ、またはHTTPSのRSS 2.0フィードを指定してください。GitHubの下書きとプレリリースは除外されます。',
        'headline_template': '見出しのテンプレート',
        'summary_template': '本文のテンプレート',
        'template_help': 'プロジェクト名は $project、更新の見出しは $title、説明は $summary、出典リンクは $url。ドル記号には $$ '
                         'を使います。見出しは160文字、本文は3,000文字以内です。',
        'check_updates': '更新の確認間隔',
        'hourly': '1時間ごと',
        'six_hourly': '6時間ごと',
        'daily': '毎日',
        'enable_auto': '新しい更新をウェブサイトとRSSに自動公開する。',
        'auto_help': '有効にした後の更新のみ公開します。停止するにはチェックを外して保存してください。アカウント全体で24時間に最大5件公開できます。',
        'auto_consent': 'このプロジェクトとニュース取得元を所有または代表し、このテンプレートと表示名による公開を許可します。所有権は自己申告です。',
        'preview_example': 'サンプルでプレビュー',
        'save_settings': '設定を保存',
        'news_footer': 'テンプレートに沿って、元の更新へのリンク付きでニュースを公開します。',
        'community_nav': 'コミュニティのナビゲーション'},
 'ko': {'write_title': '기사 작성',
        'community_stories': '커뮤니티 기사',
        'write_intro': '직접 한 일을 기사로 전해 보세요. 어떤 일이 있었고 무엇을 배웠는지, 다른 사람은 어떻게 참여할 수 있는지 공유하세요.',
        'back_feed': '소식 목록으로',
        'post_project': '프로젝트 소개',
        'manage_news': '자동 소식 관리',
        'signed_in': '로그인 계정:',
        'sign_out': '로그아웃',
        'preview_unpublished': '미리보기 · 미게시',
        'self_reported': '작성자 직접 제공',
        'take_part': '참여 방법',
        'evidence': '근거 링크',
        'link': '링크',
        'no_evidence': '작성자 직접 제공 · 근거 링크 없음.',
        'show_original': '원문 보기',
        'your_update': '전할 소식',
        'english_notice': '제목과 본문은 영어로 작성해 주세요. 작성한 내용 그대로 게시되며, 다른 언어판에는 번역이 준비될 때까지 번역 안내가 표시됩니다.',
        'project_name': '프로젝트 이름',
        'optional': '(선택)',
        'project_example': '예: Open Civic Map',
        'headline': '제목 (영어)',
        'headline_placeholder': '간결하고 사실에 충실한 영어 제목',
        'description': '어떤 일이 있었나요? (영어)',
        'description_placeholder': '무엇을 했나요? 무엇이 달라졌나요?',
        'take_part_placeholder': '참여할 곳과 필요한 도움',
        'hashtags': '해시태그',
        'hashtag_help': '공백이나 쉼표로 구분해 최대 8개까지 입력할 수 있습니다. 태그를 누르면 관련 기사를 시간순으로 볼 수 있습니다. 모든 언어의 문자, 숫자, 하이픈, '
                        '밑줄을 사용할 수 있습니다.',
        'optional_line': '(선택, 한 줄에 하나)',
        'evidence_help': '공개된 풀 리퀘스트, 회의록, 행사 페이지 등의 링크를 최대 5개까지 추가할 수 있습니다. 근거 링크가 없는 기사는 출처 없음으로 표시됩니다.',
        'original': '원문',
        'optional_language': '(선택, 모든 언어)',
        'original_placeholder': '원래 게시물이나 메모를 기사와 함께 보관하세요',
        'event_date': '발생 날짜',
        'optional_today': '(선택, 기본값은 오늘)',
        'author': '공개 표시 이름',
        'story_consent': '직접 수행한 작업이거나 공유 권한을 받았습니다. 이 기사와 링크, 원문, 표시 이름을 공개하는 데 동의합니다.',
        'story_limit': 'Google은 계정만 확인하며 기사 내용은 작성자가 직접 제공합니다. 24시간마다 기사 또는 프로젝트를 최대 5개 게시할 수 있습니다.',
        'preview_story': '기사 미리보기',
        'retry_story': '저장된 기사 게시 재시도',
        'publish_story': '기사 게시',
        'stories_footer': '직접 참여한 사람들이 전하는 커뮤니티 기사.',
        'community_projects': '커뮤니티 프로젝트',
        'submit_heading': '만들고 있는 것을 공유하세요.',
        'submit_intro': '시빅테크 프로젝트를 rep0rter 커뮤니티 소식에 소개하세요.',
        'submit_notice': '설명은 작성한 그대로 웹사이트와 RSS에 게시되며 프로젝트 소유자의 투고로 표시됩니다.',
        'project_url': '프로젝트 웹사이트 또는 저장소',
        'project_description': '프로젝트 설명',
        'project_description_help': '무엇을 하는지, 누구를 위한 것인지, 어떻게 도울 수 있는지 적어 주세요. 최대 3,000자.',
        'description_language': '설명 언어',
        'project_consent': '이 프로젝트의 소유자이거나 대표 권한을 받았으며 설명, 링크, 표시 이름을 공개하는 데 동의합니다.',
        'project_limit': 'Google 로그인은 계정만 확인합니다. 프로젝트 소유권은 직접 신고합니다. 24시간마다 프로젝트를 최대 5개 게시할 수 있습니다.',
        'retry_project': '저장된 프로젝트 게시 재시도',
        'publish_project': '프로젝트 소식 게시',
        'projects_footer': '직접 만든 사람들이 공유하는 커뮤니티 프로젝트.',
        'project_news': '내 프로젝트 소식',
        'newsroom': '내 프로젝트 편집실',
        'news_heading': '프로젝트의 소식을 이곳에서 전하세요.',
        'news_intro': '템플릿을 한 번 작성하면 프로젝트에 새 소식이 있을 때 자동으로 게시합니다.',
        'one_off': '일회성 게시물 작성',
        'add_project': '프로젝트 추가',
        'saved': '프로젝트 설정을 저장했습니다.',
        'auto_enabled': '새 소식의 자동 게시가 활성화되었습니다.',
        'auto_paused': '자동 게시가 일시 중지되었습니다.',
        'your_projects': '내 프로젝트',
        'auto_every': '자동 · {hours}시간마다',
        'paused': '일시 중지',
        'template_preview': '템플릿 미리보기 · 예시 소식',
        'sample_notice': '예시 내용입니다. 미리보기는 설정을 저장하거나 게시물을 게시하지 않습니다.',
        'edit_news': '프로젝트 소식 편집',
        'setup_news': '프로젝트 소식 설정',
        'latest_update': '최근 게시된 소식',
        'website': '프로젝트 웹사이트',
        'news_language': '소식 언어',
        'source_kind': '소식을 가져올 곳',
        'github_releases': 'GitHub 릴리스',
        'rss_feed': 'RSS 소식 피드',
        'source_url': 'GitHub 저장소 또는 RSS URL',
        'source_placeholder': 'your-team/your-project 또는 https://your-project.org/feed.xml',
        'source_help': '직접 관리하는 공개 저장소 또는 HTTPS RSS 2.0 피드를 사용하세요. GitHub 초안 및 사전 릴리스는 제외됩니다.',
        'headline_template': '소식 제목 템플릿',
        'summary_template': '소식 본문 템플릿',
        'template_help': '프로젝트 이름은 $project, 업데이트 제목은 $title, 설명은 $summary, 출처 링크는 $url을 사용하세요. 달러 기호는 $$로 '
                         '입력하세요. 제목은 160자, 본문은 3,000자 이내여야 합니다.',
        'check_updates': '새 소식 확인',
        'hourly': '매시간',
        'six_hourly': '6시간마다',
        'daily': '매일',
        'enable_auto': '새 소식을 웹사이트와 RSS에 자동 게시합니다.',
        'auto_help': '게시를 활성화한 이후의 소식만 포함됩니다. 중지하려면 선택을 해제하고 저장하세요. 계정의 모든 프로젝트를 합해 24시간마다 최대 5개 게시할 수 있습니다.',
        'auto_consent': '이 프로젝트와 소식 출처의 소유자 또는 대표이며 이 템플릿과 표시 이름을 사용한 공개 게시를 허가합니다. 소유권은 직접 신고합니다.',
        'preview_example': '예시로 미리보기',
        'save_settings': '프로젝트 설정 저장',
        'news_footer': '템플릿에 따라 각 원본 소식의 링크와 함께 프로젝트 소식을 게시합니다.',
        'community_nav': '커뮤니티 탐색'}}

# A failed language request must leave an in-progress draft intact.
ACCOUNT_COPY['en']['language_error'] = 'Could not change the language. Your draft is still here; please try again.'
ACCOUNT_COPY['zh-TW']['language_error'] = '無法切換語言。你的草稿仍保留在這裡，請再試一次。'
ACCOUNT_COPY['ja']['language_error'] = '言語を切り替えられませんでした。下書きはそのままです。もう一度お試しください。'
ACCOUNT_COPY['ko']['language_error'] = '언어를 변경하지 못했습니다. 작성 중인 내용은 그대로 있습니다. 다시 시도해 주세요.'
