name: Scrape g0v-slack-archive.g0v.ronny.tw Website

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 every day

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper
      run: python 1-parse-g0v-slack.py

    - name: Commit and push if there are changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add -A
        git commit -m "Update messages.json" -a || exit 0
        git push
